### ISSUE TITLE
Pdf is broken

### ISSUE THREAD

**Issue by BenBorn** [cy4n/talk-securitytesting#1]
Hi it looks that the Pdf-File in the repo is broken. I get allways an error that the file is corrupted.

**Comment by cy4n** [comment]
hi ben, sory for the late answer, was at a conference all week.

how did you try to open the pdf? i have downloaded and successfully opened it in MacOSs preview.app and also in the gnome Document Viewer in Linux.

**Comment by BenBorn** [comment]
I use chrome and If I download the file to my Windows PC and open it "Acrobate Reader" tells me that its broken. Also if I open the file directly in chrome its failing as well. Other kind of pdf-Files I can open without a problem.

**Comment by cy4n** [comment]
i've added the slides to slideshare as a workaround. 
https://www.slideshare.net/ChristianKhn8/automated-security-testing-in-continuous-integration

PDF was exported from apple keynote, maybe the problem is buried there. 
tbh probably i won't look into it any further

**Comment by BenBorn** [comment]
Perfect thanks
